disabled: false
field_template: true
ft-default: default
ft-show-colon: false
classes:
  region:
    - bg|background
    - col
    - col-lg-3
    - col-md-4
  field:
    - img-fluid
    - float-left
    - float-right
use_field_names: true
_core:
  default_config_hash: xfB0qOeoAomOThclNNokdKTrVwXLcXz13SU3-4a5-FY
